### ISSUE TITLE
bintrayUpload seems not working

### ISSUE THREAD

**Issue by faruktoptas** [wajahatkarim3/JCenter-Gradle-Scripts#1]
Hi @wajahatkarim3 I've been using your gradle scripts to upload my libraries (Steps from this blog post https://android.jlelse.eu/publishing-your-android-kotlin-or-java-library-to-jcenter-from-android-studio-1b24977fe450) 
It was working until now but I think It doesn't work now. bintrayUplad scripts runs very fast (less than a second) without any error. 
Did you faced this error?

**Comment by faruktoptas** [comment]
I fixed it :)
bintray.user and bintray.apikey was missing in my local.properties file.
It would save my hours if there was an error message to show those missing parts.

**Comment by wajahatkarim3** [comment]
Thank you for your feedback. I don't know how I missed this as I just saw this. I will update the script to show a message if there's no username or api key in the local.properties file.
